#!/bin/bash
# export-test-db.sh - Export lightweight test database for E2E testing
# Usage: ./tests/e2e/fixtures/export-test-db.sh [output_file]
#
# Runs mysqldump via Docker container against the abr-mysql service

set -e
set -o pipefail

OUTPUT_FILE="${1:-tests/e2e/fixtures/test-seed.sql.gz}"
DB_HOST="mysql"
DB_USER="root"
DB_PASS="rootsecret"
DB_NAME="netrunner"

# Test user IDs
TEST_USER_IDS="1276,21903"

# Days for recency filter
RECENCY_DAYS=120

echo "Exporting test database to $OUTPUT_FILE..."

# Calculate cutoff date (120 days ago) - works on both macOS and Linux
if date -v-1d > /dev/null 2>&1; then
  # macOS
  CUTOFF_DATE=$(date -v-${RECENCY_DAYS}d +%Y-%m-%d)
else
  # Linux
  CUTOFF_DATE=$(date -d "${RECENCY_DAYS} days ago" +%Y-%m-%d)
fi
echo "Cutoff date for recent data: $CUTOFF_DATE"

# Create output directory if needed
mkdir -p "$(dirname "$OUTPUT_FILE")"

# Helper function to run mysqldump via Docker
mysqldump_docker() {
    docker compose exec -T mysql mysqldump -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$@" 2>/dev/null
}

# Work with uncompressed file during export, compress at end
UNCOMPRESSED_FILE="${OUTPUT_FILE%.gz}"

# Start with header
cat > "$UNCOMPRESSED_FILE" << 'EOF'
-- AlwaysBeRunning Test Database Seed
-- Auto-generated by scripts/export-test-db.sh - do not edit manually
-- Contains filtered production data for E2E testing

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET FOREIGN_KEY_CHECKS = 0;
SET AUTOCOMMIT = 0;
START TRANSACTION;

EOF

# ====================
# TABLES TO INCLUDE IN FULL (reference data)
# ====================
FULL_TABLES=(
    "badges"
    "countries"
    "tournament_types"
    "tournament_formats"
    "card_cycles"
    "card_packs"
    "card_identities"
    "mwls"
    "artists"
    "prizes"
    "prize_elements"
    "tournament_groups"
    "video_tags"
)

echo "Exporting full tables..."
for table in "${FULL_TABLES[@]}"; do
    echo "  - $table"
    mysqldump_docker --no-create-info --single-transaction --skip-lock-tables \
        "$DB_NAME" "$table" >> "$UNCOMPRESSED_FILE" || echo "    (table may be empty or not exist)"
done

# ====================
# USERS TABLE - Export test users + users referenced by tournaments and entries
# ====================
echo "Finding users referenced by exported data..."
# Get user IDs from tournaments (creator) and entries (user) that match our export criteria
# Capture mysql output separately to detect failures (pipefail catches errors, but validate result too)
MYSQL_OUTPUT=$(docker compose exec -T mysql mysql -N -h "$DB_HOST" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" -e "
    SELECT DISTINCT id FROM (
        -- Test users
        SELECT id FROM users WHERE id IN ($TEST_USER_IDS)
        UNION
        -- Tournament creators (recent tournaments)
        SELECT DISTINCT creator AS id FROM tournaments WHERE updated_at >= '$CUTOFF_DATE' AND creator IS NOT NULL
        UNION
        -- Entry users (test users + recent entries)
        SELECT DISTINCT user AS id FROM entries WHERE (user IN ($TEST_USER_IDS) OR updated_at >= '$CUTOFF_DATE') AND user IS NOT NULL
    ) AS all_users;
" 2>/dev/null)

REFERENCED_USERS=$(echo "$MYSQL_OUTPUT" | tr '\n' ',' | sed 's/,$//')

# Validate we got results (test users should always exist)
if [ -z "$REFERENCED_USERS" ]; then
    echo "ERROR: Failed to find referenced users. Check database connection and that test users ($TEST_USER_IDS) exist." >&2
    exit 1
fi

echo "Exporting users (referenced by tournaments/entries)..."
echo "  User IDs: $REFERENCED_USERS"
mysqldump_docker --no-create-info --single-transaction --skip-lock-tables \
    --where="id IN ($REFERENCED_USERS)" \
    "$DB_NAME" users >> "$UNCOMPRESSED_FILE"

# ====================
# BADGE_USER - Only test users
# ====================
echo "Exporting badge_user (test users only)..."
mysqldump_docker --no-create-info --single-transaction --skip-lock-tables \
    --where="user_id IN ($TEST_USER_IDS)" \
    "$DB_NAME" badge_user >> "$UNCOMPRESSED_FILE"

# ====================
# PHOTOS - Only test users
# ====================
echo "Exporting photos (test users only)..."
mysqldump_docker --no-create-info --single-transaction --skip-lock-tables \
    --where="user_id IN ($TEST_USER_IDS)" \
    "$DB_NAME" photos >> "$UNCOMPRESSED_FILE"

# ====================
# PRIZE_COLLECTIONS - Only test users
# ====================
echo "Exporting prize_collections (test users only)..."
mysqldump_docker --no-create-info --single-transaction --skip-lock-tables \
    --where="user_id IN ($TEST_USER_IDS)" \
    "$DB_NAME" prize_collections >> "$UNCOMPRESSED_FILE"

# ====================
# TOURNAMENTS - Recent OR created by test users
# ====================
echo "Exporting tournaments (recent + test-user-created)..."
mysqldump_docker --no-create-info --single-transaction --skip-lock-tables \
    --where="updated_at >= '$CUTOFF_DATE' OR creator IN ($TEST_USER_IDS)" \
    "$DB_NAME" tournaments >> "$UNCOMPRESSED_FILE"

# ====================
# ENTRIES - Test users OR recent
# Note: `user` column (not `user_id`) holds the user foreign key
# ====================
echo "Exporting entries (test users + recent)..."
mysqldump_docker --no-create-info --single-transaction --skip-lock-tables \
    --where="user IN ($TEST_USER_IDS) OR updated_at >= '$CUTOFF_DATE'" \
    "$DB_NAME" entries >> "$UNCOMPRESSED_FILE"

# ====================
# VIDEOS - recent only (videos table has created_at)
# ====================
echo "Exporting videos (recent only)..."
mysqldump_docker --no-create-info --single-transaction --skip-lock-tables \
    --where="created_at >= '$CUTOFF_DATE'" \
    "$DB_NAME" videos >> "$UNCOMPRESSED_FILE"

# ====================
# SKIP THESE TABLES
# ====================
# - sessions (runtime data, not needed)
# - migrations (Laravel internal, auto-created)

# Footer
cat >> "$UNCOMPRESSED_FILE" << 'EOF'

SET FOREIGN_KEY_CHECKS = 1;
COMMIT;
EOF

# Compress the output
UNCOMPRESSED_FILE="${OUTPUT_FILE%.gz}"
if [[ "$OUTPUT_FILE" == *.gz ]]; then
    echo "Compressing $UNCOMPRESSED_FILE..."
    gzip -f "$UNCOMPRESSED_FILE"
else
    # If output doesn't end in .gz, compress and rename
    gzip -f "$OUTPUT_FILE"
    OUTPUT_FILE="$OUTPUT_FILE.gz"
fi

# Show file size
FILE_SIZE=$(ls -lh "$OUTPUT_FILE" | awk '{print $5}')

echo ""
echo "Export complete: $OUTPUT_FILE"
echo "  Compressed size: $FILE_SIZE"
