{{--Table of tournament infos, data generated by AJAX front-end--}}
<h5>
    @unless (empty($icon))
        <i class="fa {{ $icon }}" aria-hidden="true"></i>
    @endunless
    {{ $title }}
    @unless (empty($subtitle))
        <br/>
        <small>{{ $subtitle }}</small>
    @endunless
</h5>
@unless (empty($loader))
    <div class="loader">&nbsp;</div>
@endunless
<table class="table table-sm table-striped abr-table{{ @$doublerow ? ' table-doublerow' : '' }}" id="{{ $id }}">
    <thead>
        @if( in_array('title', $columns) )
            <th>title</th>
        @endif
        @if( in_array('date', $columns) )
            <th>date</th>
        @endif
        @if( in_array('location', $columns) )
            <th>location</th>
        @endif
        @if( in_array('recurday', $columns) )
            <th>day of the week</th>
        @endif
        @if( in_array('cardpool', $columns) )
            <th>cardpool</th>
        @endif
        @if( in_array('type', $columns) )
            <th class="hidden-md-down">type</th>
        @endif
        @if( in_array('approval', $columns) )
            <th class="text-xs-center">approval</th>
        @endif
        @if( in_array('user_claim', $columns) )
            <th class="text-xs-center">claim</th>
        @endif
        @if( in_array('conclusion', $columns) )
            <th class="text-xs-center">conclusion</th>
        @endif
        @if( in_array('winner', $columns) )
            <th class="text-xs-center">1st</th>
        @endif
        @if( in_array('players', $columns) )
            <th class="text-xs-center hidden-sm-down">players</th>
            <th class="text-xs-center hidden-xs-down hidden-md-up">
                @include('partials.popover', ['direction' => 'top', 'content' => 'players'])
            </th>
        @endif
        @if( in_array('claims', $columns) )
            <th class="text-xs-center hidden-sm-down">claims</th>
            <th class="text-xs-center hidden-xs-down hidden-md-up">
                @include('partials.popover', ['direction' => 'top', 'content' => 'claims'])
            </th>
        @endif
        @if( in_array('action_view', $columns) )
            <th></th>
        @endif
        @if( in_array('action_edit', $columns) )
            <th></th>
        @endif
        @if( in_array('action_approve', $columns) )
            <th></th>
        @endif
        @if( in_array('action_reject', $columns) )
            <th></th>
        @endif
        @if( in_array('action_delete', $columns) )
            <th></th>
        @endif
        @if( in_array('action_restore', $columns) )
            <th></th>
        @endif
    </thead>
    <tbody></tbody>
</table>
<div class="text-xs-center hidden-xs-up small-text" id="{{ $id }}-controls" data-maxrows="{{ @$maxrows }}" data-currentpage="1"
        data-totalrows="0" data-torows="0">
    <a onclick="doTournamentPaging('{{ $id }}', false)" class="fake-link hidden-xs-up" id="{{ $id }}-controls-back">
        <i class="fa fa-chevron-circle-left" aria-hidden="true"></i>
    </a>
    showing <span id="{{ $id }}-number-from">1</span>-<span id="{{ $id }}-number-to">{{ @$maxrows }}</span> of <span id="{{ $id }}-number-total"></span>
    <a onclick="doTournamentPaging('{{ $id }}', true)" class="fake-link" id="{{ $id }}-controls-forward">
        <i class="fa fa-chevron-circle-right" aria-hidden="true"></i><br/>
    </a>
</div>