{{--Table of tournament infos, data generated by AJAX front-end--}}
@unless(@$skip_header)
    <h5 id="{{ $id }}-title">
        @unless (empty($icon))
            <i class="fa {{ $icon }}" aria-hidden="true"></i>
        @endunless
        {{ @$title }}
        @unless (empty($subtitle))
            <br/>
            <small>{{ $subtitle }}</small>
        @endunless
    </h5>
@endunless
@unless (empty($loader))
    <div class="loader" id="{{ $id }}-loader">&nbsp;</div>
@endunless
<table class="table table-sm table-striped abr-table{{ @$doublerow ? ' table-doublerow' : '' }}" id="{{ $id }}">
    <thead>
        @if( in_array('title', $columns) )
            <th>title</th>
        @endif
        @if( in_array('date', $columns) )
            <th>date</th>
        @endif
        @if( in_array('location', $columns) )
            <th class="hidden-sm-down">location</th>
            <th class="text-xs-center hidden-md-up">
                <i class="fa fa-globe" title="location"></i>
            </th>
        @endif
        @if( in_array('recurday', $columns) )
            <th>day of the week</th>
        @endif
        @if( in_array('cardpool', $columns) )
            <th>cardpool</th>
        @endif
        @if( in_array('creator', $columns) )
            <th>creator</th>
        @endif
        @if( in_array('type', $columns) )
            <th class="hidden-md-down">type</th>
        @endif
        @if( in_array('approval', $columns) )
            <th class="text-xs-center">
                <span class="hidden-md-down">approval</span>
                <i class="fa fa-check hidden-lg-up" aria-hidden="true"></i>
            </th>
        @endif
        @if( in_array('user_claim', $columns) )
            <th class="text-xs-center">claim</th>
        @endif
        @if( in_array('conclusion', $columns) )
            <th class="text-xs-center">conclusion</th>
        @endif
        @if( in_array('winner', $columns) )
            <th class="text-xs-center">1st</th>
        @endif
        @if( in_array('players', $columns) )
            <th class="text-xs-center hidden-sm-down">players</th>
            <th class="text-xs-center hidden-xs-down hidden-md-up">
                <i class="fa fa-user" title="players"></i>
            </th>
        @endif
        @if( in_array('regs', $columns) )
            <th class="text-xs-center hidden-sm-down">going</th>
            <th class="text-xs-center hidden-xs-down hidden-md-up">
                <i class="fa fa-registered" title="players going"></i>
            </th>
        @endif
        @if( in_array('claims', $columns) )
            <th class="text-xs-center hidden-sm-down">claims</th>
            <th class="text-xs-center hidden-xs-down hidden-md-up">
                <i class="fa fa-address-card" title="claims"></i>
            </th>
        @endif
        @if( in_array('created_at', $columns) )
            <th class="text-xs-center">created at</th>
        @endif
        @if( in_array('action_view', $columns) )
            <th></th>
        @endif
        @if( in_array('action_edit', $columns) )
            <th></th>
        @endif
        @if( in_array('action_approve', $columns) )
            <th></th>
        @endif
        @if( in_array('action_reject', $columns) )
            <th></th>
        @endif
        @if( in_array('action_delete', $columns) )
            <th></th>
        @endif
        @if( in_array('action_purge', $columns) )
            <th></th>
        @endif
        @if( in_array('action_restore', $columns) )
            <th></th>
        @endif
    </thead>
    <tbody></tbody>
</table>
@include('tournaments.partials.pager',
    ['id' => $id, 'maxrows' => @$maxrows, 'flag_switcher' => in_array('location', $columns)])